version: "3.9"
services: 

  database:
    container_name: portvis-db
    image: mysql:8
    environment: 
      MYSQL_DATABASE: portvisdb
      MYSQL_USER: portvis
      MYSQL_PASSWORD: portvis
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"

  server:
    container_name: portvis-server
    build: ./server
    environment: 
      MYSQL_DB_HOST: database # 1.
      MYSQL_DB_PORT: 3306

      MYSQL_DB_NAME: portvisdb
      MYSQL_DB_USERNAME: portvis
      MYSQL_DB_PASSWORD: portvis

      CORS_ALLOWED_ORIGIN: http://localhost
    ports:
      - "8080:8080"
    depends_on:
      - database

  client:
    container_name: portvis-client
    build:
      context: ./client # 2.
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
    depends_on:
      - server

# 1. This means Spring Boot is expecting database:3306
# 2. Dockerfile for regular build (building from source code)
#    Dockerfile.prod to skip RAM-hungry 'npm run build' step
